name: Create release from tag
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10'
    - run: ./publish.sh
    - uses: actions/upload-artifact@v6
      with:
        name: publish_artifact
        path: _publish
  release:
    needs: build
    runs-on: ubuntu-latest
    concurrency: publish-release
    permissions:
      contents: write
    steps:
      #- uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with:
          name: publish_artifact
      - uses: ghalactic/github-release-from-tag@v6
        with:
          assets: |
            - path: _publish
              name: test_asset
              label: test asset label
