name: Create release from tag
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10'
    - run: ./publish.sh
    - uses: actions/upload-artifact@v6
      with:
        name: publish
        path: _publish
  release:
    needs: build
    runs-on: ubuntu-latest
    concurrency: publish-release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: ghalactic/github-release-from-tag@v6
        with:
          assets: |
            - path: publish
              name: publish_asset_test
              label: publish asset label test
